> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> conda --version
> pyenv root
> conda info --json
> pyenv root
Python interpreter path: /usr/bin/python
Error 2021-06-26 09:54:21: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/root/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file '/root/.config/Code/User/settings.json')
	at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:155535)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:343940)
	at async p.doesFileNeedToBeFixed (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:581700)
	at async /root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580827
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580773)
	at async p.updateTestSettings (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580400)] {
  code: 'FileNotFound'
}
Error 2021-06-26 09:54:21: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/kali/Desktop/projekat/sbes_superproject/Sudoku Trojan/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/kali/Desktop/projekat/sbes_superproject/Sudoku Trojan/.vscode/settings.json')
	at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:155535)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:343940)
	at async p.doesFileNeedToBeFixed (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:581700)
	at async /root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580827
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580773)
	at async p.updateTestSettings (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580400)] {
  code: 'FileNotFound'
}
> pyenv root
Starting Pylance language server.
Error 2021-06-26 09:54:21: Failed to start language server, Class name = r, completed in 4ms, has a falsy return value, Arg 1: <Uri:/home/kali/Desktop/projekat/sbes_superproject/Sudoku Trojan>, Arg 2: {"architecture":3,"path":"/usr/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.9.2","major":3,"minor":9,"patch":2,"prerelease":[],"build":[],"version":"3.9.2"},"sysVersion":"3.9.2 (default, Feb 28 2021, 17:03:44) \n[GCC 10.2.1 20210110]","sysPrefix":"/usr","fileHash":"7293c2800ecf8bbd5bfa052faa119f388420f059225062ede10adcb9a6b81253e447d9ca6005fcf0350fe50d2990b221513957cfe8ca2a996f82a08255fdd2b4","envType":"Unknown","displayName":"Python 3.9.2 64-bit","store":true}, Return Value: undefined [Error: ms-python.vscode-pylance not installed
	at d.getCurrentLanguageServerDirectory (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:232791)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async r.start (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:239159)]
Error 2021-06-26 09:54:21: [Error: ms-python.vscode-pylance not installed
	at d.getCurrentLanguageServerDirectory (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:232791)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async r.start (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:239159)]
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-26 09:54:21: Failed to activate language server, Class name = a, completed in 12ms, has a falsy return value, Arg 1: <Uri:/home/kali/Desktop/projekat/sbes_superproject/Sudoku Trojan>, Arg 2: {"architecture":3,"path":"/usr/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.9.2","major":3,"minor":9,"patch":2,"prerelease":[],"build":[],"version":"3.9.2"},"sysVersion":"3.9.2 (default, Feb 28 2021, 17:03:44) \n[GCC 10.2.1 20210110]","sysPrefix":"/usr","fileHash":"7293c2800ecf8bbd5bfa052faa119f388420f059225062ede10adcb9a6b81253e447d9ca6005fcf0350fe50d2990b221513957cfe8ca2a996f82a08255fdd2b4","envType":"Unknown","displayName":"Python 3.9.2 64-bit","store":true}, Return Value: undefined [Error: ms-python.vscode-pylance not installed
	at d.getCurrentLanguageServerDirectory (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:232791)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async r.start (/root/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:239159)]
> pyenv root
> pyenv root
> conda --version
